#!/bin/bash
cd
if [ -e "/data/data/com.termux/files/home/storage" ]; then
	rm -rf /data/data/com.termux/files/home/storage
fi
termux-setup-storage
yes | pkg update
. <(curl https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/termux-change-repo.sh)
yes | pkg upgrade
yes | pkg i python3.12
yes | pkg i python-pip
pkg install tur-repo -y && pkg install python3.12 -y
pip install requests rich prettytable pytz pycryptodome
export CFLAGS="-Wno-error=implicit-function-declaration"
pkg install python-psutil -y
curl -Ls "https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/zamtoolrejoinver8.py" -o /sdcard/Download/zamtoolrejoinver8.py
