#!/bin/ba#!/bin/bash
cd
[ -e "/data/data/com.termux/files/home/storage" ] && rm -rf /data/data/com.termux/files/home/storage
termux-setup-storage
yes | pkg update
. <(curl https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/termux-change-repo.sh)
yes | pkg upgrade

# Cài tur-repo TRƯỚC rồi mới cài python3.12
pkg install tur-repo -y
pkg install python3.12 -y
yes | pkg i python-pip

export CFLAGS="-Wno-error=implicit-function-declaration"  

pip install requests rich prettytable pytz pycryptodome
pkg install python-psutil -y   

curl -Ls "https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/zamtoolrejoinver8.py" \
  -o /sdcard/Download/zamtoolrejoinver8.py
